sudo: false
language: node_js
node_js:
  - "0.10"
env:
  global:
    secure: "15QWA6igmMx1I2YlDrdkxsOi2YJIWNrXmgEtfEoCWR7eJQW2bkUDdzTXYFzxaEPIVMEgO+0pxfGwMWn/9MBhnXCLu9x0f0KqJ/0YfCGXHW21g8J+31zypdiCiw/Ir/dxazP9wpvWFhuqjo9X35zP3Md7TC8u+20uW2Q5KUVyqZM="
before_install:
  - openssl aes-256-cbc -K $encrypted_909ac1036a94_key -iv $encrypted_909ac1036a94_iv -in .travis/govuk_frontend_toolkit_push.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git remote add origin_ssh git@github.com:alphagov/govuk_frontend_toolkit.git
  - bundle install
script:
  - npm test
deploy:
  - provider: script
    script: './push.sh'
    on:
      branch: master
  - provider: script
    script: './trigger.sh'
    on:
      branch: master
